language: node_js
dist: trusty
sudo: required
node_js:
  - "7"
  - "6"
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - npm rebuild phantom-prebuilt
  - node spec/integration/server.js &
  - npm run test
