language: node_js
dist: trusty
sudo: required
node_js:
  - "7"
  - "6"
cache:
  directories:
    - node_modules
before_install:
  - "npm install --global yarn"
install:
  - yarn install
script:
  - node spec/integration/server.js &
  - npm run test
